In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
steam_data = pd.read_csv('final-project-data-combined.csv')

In [3]:
steam_data.head()

,App Id,Name,Developers,Publishers,Metascores,Owners,Genres,Tags,Price
0,7,Steam Client,NaN,NaN,NaN,"0Â ..Â 20,000",[''],NaN,$0.00
1,8,winui2,NaN,NaN,NaN,"0Â ..Â 20,000",[''],NaN,$0.00
2,10,Counter-Strike,Valve,Valve,88%,"10,000,000Â ..Â 20,000,000",['Action'],"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",$9.99
3,20,Team Fortress Classic,Valve,Valve,NaN,"2,000,000Â ..Â 5,000,000",['Action'],"['Action', 'FPS', 'Multiplayer', 'Classic', 'H...",$4.99
4,30,Day of Defeat,Valve,Valve,79%,"5,000,000Â ..Â 10,000,000",['Action'],"['FPS', 'World War II', 'Multiplayer', 'Shoote...",$4.99

In [4]:
new = steam_data["Owners"].str.split("Â ..Â ", n = 1, expand = True)
steam_data['Owners'].dtypes
new

                0           1
0               0      20,000
1               0      20,000
2      10,000,000  20,000,000
3       2,000,000   5,000,000
4       5,000,000  10,000,000
...           ...         ...
95239           0      20,000
95240           0      20,000
95241           0      20,000
95242           0      20,000
95243           0      20,000

[95244 rows x 2 columns]

In [5]:
steam_data["min owners"] = new[0]
steam_data["max owners"] = new[1]
steam_data.drop(columns =["Owners"], inplace = True)

In [6]:
steam_data

,App Id,Name,Developers,Publishers,Metascores,Genres,Tags,Price,min owners,max owners
0,7,Steam Client,NaN,NaN,NaN,[''],NaN,$0.00,0,"20,000"
1,8,winui2,NaN,NaN,NaN,[''],NaN,$0.00,0,"20,000"
2,10,Counter-Strike,Valve,Valve,88%,['Action'],"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",$9.99,"10,000,000","20,000,000"
3,20,Team Fortress Classic,Valve,Valve,NaN,['Action'],"['Action', 'FPS', 'Multiplayer', 'Classic', 'H...",$4.99,"2,000,000","5,000,000"
4,30,Day of Defeat,Valve,Valve,79%,['Action'],"['FPS', 'World War II', 'Multiplayer', 'Shoote...",$4.99,"5,000,000","10,000,000"
...,...,...,...,...,...,...,...,...,...,...
95239,1474820,The Tower Of TigerQiuQiu Tiger Tank 60,TigerQiuQiu,TigerQiuQiu,NaN,"['Action', 'Casual', 'Indie']",NaN,$0.74,0,"20,000"
95240,1474960,Der Geisterturm / The Ghost Tower Demo,Graverobber Foundation,Graverobber Foundation,NaN,[''],NaN,$0.00,0,"20,000"
95241,1475910,DIY Simulator Dedicated Server,NaN,NaN,NaN,[''],NaN,$0.00,0,"20,000"
95242,1476030,OTTI'S QUEST,NaN,NaN,NaN,[''],NaN,$0.00,0,"20,000"
95243,2028850,Bioshock Infinite: Columbia's Finest,Irrational Games,2K Games,NaN,['Action'],"['Action', 'FPS', 'Singleplayer']",$4.99,0,"20,000"

In [ ]:
# new_max = steam_data["max"].str.split(".", n = 1, expand = True)
# new_max[1]

In [ ]:
# steam_data["max"] = new_max[1]
# steam_data

In [ ]:
#  steam_data["Genres"] = steam_data["Genres"].apply(eval)

In [22]:
steam_data_clean = steam_data.dropna(subset=["Genres", "Developers","Tags","Metascores", "max owners", "min owners"])

In [23]:
steam_data_clean.shape

(4005, 10)

In [24]:
steam_data_clean.isna().sum()

App Id         0
Name           0
Developers     0
Publishers    61
Metascores     0
Genres         0
Tags           0
Price          0
min owners     0
max owners     0
dtype: int64

In [ ]:
# steam_data_clean["Genres"] = steam_data_clean["Genres"].replace("'","")

In [ ]:
# steam_data_clean.head()

In [ ]:
# stripped_genres = []

# for i in steam_data_clean["Genres"]:
#     x = i.replace("'","")
#     stripped_genres.append(x)
    
# len(stripped_genres)

In [ ]:
# stripped_genres

In [ ]:
# steam_data_clean["Genres"] = stripped_genres

In [ ]:
# steam_data_clean.head()

In [ ]:
# steam_data.head()

In [10]:
steam_data_clean["Genres"] = steam_data_clean["Genres"].apply(eval)

<ipython-input-10-3de5af67e85d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  steam_data_clean["Genres"] = steam_data_clean["Genres"].apply(eval)

In [11]:
genre_dict = {}
for i in steam_data_clean["Genres"]:
    for j in i:
        if j not in genre_dict:
            genre_dict[j] = 1
        else:
            genre_dict[j] += 1
genre_dict

{'Action': 1938,
 'Free to Play': 123,
 'Strategy': 978,
 'Adventure': 1500,
 'Indie': 1994,
 'RPG': 801,
 'Casual': 426,
 'Simulation': 527,
 'Racing': 151,
 '': 60,
 'Massively Multiplayer': 89,
 'Sports': 139,
 'in Early Access': 218,
 'Nudity': 5,
 'Violent': 30,
 'Gore': 8,
 'Early Access': 5,
 'Sexual Content': 4,
 'Movie': 5,
 'Animation & Modeling': 1,
 'Education': 1,
 'Utilities': 1,
 'Video Production': 1,
 'Documentary': 1}

In [12]:
genre_explode = steam_data_clean.explode("Genres")
genre_explode

,App Id,Name,Developers,Publishers,Metascores,Genres,Tags,Price,min owners,max owners
2,10,Counter-Strike,Valve,Valve,88%,Action,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",$9.99,"10,000,000","20,000,000"
4,30,Day of Defeat,Valve,Valve,79%,Action,"['FPS', 'World War II', 'Multiplayer', 'Shoote...",$4.99,"5,000,000","10,000,000"
8,70,Half-Life,Valve,Valve,96%,Action,"['FPS', 'Classic', 'Action', 'Sci-fi', 'Single...",$9.99,"5,000,000","10,000,000"
9,80,Counter-Strike: Condition Zero,Valve,Valve,65%,Action,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'F...",$9.99,"5,000,000","10,000,000"
12,100,Counter-Strike: Condition Zero,Valve,Valve,65%,Action,"['Action', 'FPS', 'Shooter', 'Multiplayer', 'F...",$9.99,"10,000,000","20,000,000"
...,...,...,...,...,...,...,...,...,...,...
87795,1342620,Werewolf: The Apocalypse â€” Heart of the Forest,Different Tales,Walkabout,78%,Adventure,"['Werewolves', 'Visual Novel', 'RPG', 'Psychol...",$14.99,"200,000","500,000"
87795,1342620,Werewolf: The Apocalypse â€” Heart of the Forest,Different Tales,Walkabout,78%,Indie,"['Werewolves', 'Visual Novel', 'RPG', 'Psychol...",$14.99,"200,000","500,000"
87795,1342620,Werewolf: The Apocalypse â€” Heart of the Forest,Different Tales,Walkabout,78%,RPG,"['Werewolves', 'Visual Novel', 'RPG', 'Psychol...",$14.99,"200,000","500,000"
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Action,"['Action', 'Farming Sim', 'Story Rich', 'Side ...",$39.99,"50,000","100,000"
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,"['Action', 'Farming Sim', 'Story Rich', 'Side ...",$39.99,"50,000","100,000"

In [ ]:
# steam_data_clean.head()

In [ ]:
# len(steam_data_clean["Genres"].iloc[0].replace("[", "").replace("]", "").split(","))

In [ ]:
# i = 3
# stored_data = []
# genre_series = []

# #for i in range(5):
# if len(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")) == 1:
#     stored_data.append(steam_data_clean.iloc[i, :])
#     genre_series.append(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")[0])
# elif len(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")) == 2:
#     genre_list = steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")
#     genre_series.append(genre_list[0])
#     genre_series.append(genre_list[1])
#     stored_data.append(steam_data_clean.iloc[i, :])
#     stored_data.append(steam_data_clean.iloc[i, :])
# elif len(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")) == 3:
#     genre_list = steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")
#     genre_series.append(genre_list[0])
#     genre_series.append(genre_list[1])
#     genre_series.append(genre_list[2])
#     stored_data.append(steam_data_clean.iloc[i, :])
#     stored_data.append(steam_data_clean.iloc[i, :])
#     stored_data.append(steam_data_clean.iloc[i, :])
# elif len(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")) == 4:
#     genre_list = steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")
#     genre_series.append(genre_list[0])
#     genre_series.append(genre_list[1])
#     genre_series.append(genre_list[2])
#     genre_series.append(genre_list[3])
#     stored_data.append(steam_data_clean.iloc[i, :])
#     stored_data.append(steam_data_clean.iloc[i, :])
#     stored_data.append(steam_data_clean.iloc[i, :])
#     stored_data.append(steam_data_clean.iloc[i, :])
# elif len(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")) == 5:
#     genre_list = steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")
#     genre_series.append(genre_list[0])
#     genre_series.append(genre_list[1])
#     genre_series.append(genre_list[2])
#     genre_series.append(genre_list[3])
#     genre_series.append(genre_list[4])
#     stored_data.append(steam_data_clean.iloc[i, :])
#     stored_data.append(steam_data_clean.iloc[i, :])
#     stored_data.append(steam_data_clean.iloc[i, :])
#     stored_data.append(steam_data_clean.iloc[i, :])
#     stored_data.append(steam_data_clean.iloc[i, :])

In [ ]:
# stored_data

In [ ]:
# test = pd.DataFrame(stored_data)

# test

In [ ]:
# genre_series

In [ ]:
# # create new dataframe where every column is the same EXCEPT the genres. if there is a game with 2 genres, make 2 rows where 
# # column is the same except for the genre.

# stored_data = []
# genre_series = []

# for i in range(steam_data_clean.shape[0]):
#     if len(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")) == 1:
#         stored_data.append(steam_data_clean.iloc[i, :])
#         genre_series.append(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")[0])
#     elif len(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")) == 2:
#         genre_list = steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")
#         genre_series.append(genre_list[0])
#         genre_series.append(genre_list[1])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#     elif len(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")) == 3:
#         genre_list = steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")
#         genre_series.append(genre_list[0])
#         genre_series.append(genre_list[1])
#         genre_series.append(genre_list[2])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#     elif len(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")) == 4:
#         genre_list = steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")
#         genre_series.append(genre_list[0])
#         genre_series.append(genre_list[1])
#         genre_series.append(genre_list[2])
#         genre_series.append(genre_list[3])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#     elif len(steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")) == 5:
#         genre_list = steam_data_clean["Genres"].iloc[i].replace("[", "").replace("]", "").split(",")
#         genre_series.append(genre_list[0])
#         genre_series.append(genre_list[1])
#         genre_series.append(genre_list[2])
#         genre_series.append(genre_list[3])
#         genre_series.append(genre_list[4])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])

In [ ]:
# genre_df = pd.DataFrame(stored_data)

# genre_df.head(10)

In [ ]:
# genre_df["Genres"] = genre_series

# genre_df.head()

In [ ]:
# # # create new dataframe where every column is the same EXCEPT the genres. if there is a game with 2 genres, make 2 rows where 
# # # column is the same except for the genre.

# stored_data_tags = []
# Tags_series = []

# for i in range(genre_explode.shape[0]):
#     if len(steam_data_clean["Tags"].iloc[i].replace("[", "").replace("]", "").split(",")) == 1:
#         stored_data_tags.append(steam_data_clean.iloc[i, :])
#         genre_series.append(steam_data_clean["Tags"].iloc[i].replace("[", "").replace("]", "").split(",")[0])
#     elif len(steam_data_clean["Tags"].iloc[i].replace("[", "").replace("]", "").split(",")) == 2:
#         genre_list = steam_data_clean["Tags"].iloc[i].replace("[", "").replace("]", "").split(",")
#         genre_series.append(genre_list[0])
#         genre_series.append(genre_list[1])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#     elif len(steam_data_clean["Tags"].iloc[i].replace("[", "").replace("]", "").split(",")) == 3:
#         genre_list = steam_data_clean["Tags"].iloc[i].replace("[", "").replace("]", "").split(",")
#         genre_series.append(genre_list[0])
#         genre_series.append(genre_list[1])
#         genre_series.append(genre_list[2])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#     elif len(steam_data_clean["Tags"].iloc[i].replace("[", "").replace("]", "").split(",")) == 4:
#         genre_list = steam_data_clean["Tags"].iloc[i].replace("[", "").replace("]", "").split(",")
#         genre_series.append(genre_list[0])
#         genre_series.append(genre_list[1])
#         genre_series.append(genre_list[2])
#         genre_series.append(genre_list[3])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#     elif len(steam_data_clean["Tags"].iloc[i].replace("[", "").replace("]", "").split(",")) == 5:
#         genre_list = steam_data_clean["Tags"].iloc[i].replace("[", "").replace("]", "").split(",")
#         genre_series.append(genre_list[0])
#         genre_series.append(genre_list[1])
#         genre_series.append(genre_list[2])
#         genre_series.append(genre_list[3])
#         genre_series.append(genre_list[4])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])
#         stored_data.append(steam_data_clean.iloc[i, :])

In [13]:
genre_explode["Tags"] = genre_explode["Tags"].apply(eval)

In [14]:
tag_dict = {}
for i in genre_explode["Tags"]:
    for j in i:
        if j not in tag_dict:
            tag_dict[j] = 1
        else:
            tag_dict[j] += 1
tag_dict

{'Action': 5572,
 'FPS': 881,
 'Multiplayer': 2884,
 'Shooter': 1325,
 'Classic': 860,
 'Team-Based': 245,
 'First-Person': 1414,
 'Competitive': 281,
 'Tactical': 883,
 "1990's": 179,
 'e-sports': 58,
 'PvP': 433,
 'Old School': 199,
 'Military': 317,
 'Strategy': 2957,
 'Survival': 903,
 'Score Attack': 61,
 '1980s': 87,
 'Assassin': 74,
 'Violent': 711,
 'World War II': 229,
 'War': 430,
 'Class-Based': 64,
 'Historical': 552,
 'Co-op': 1863,
 'Singleplayer': 6124,
 'Difficult': 1526,
 'World War I': 34,
 'Retro': 856,
 'Sci-fi': 1715,
 'Aliens': 210,
 'Story Rich': 2242,
 'Adventure': 5202,
 'Silent Protagonist': 30,
 'Atmospheric': 2807,
 'Great Soundtrack': 3135,
 'Moddable': 425,
 'Linear': 88,
 'Gore': 833,
 'Online Co-Op': 726,
 'Open World': 1684,
 'Simulation': 1981,
 'Dark': 571,
 'Masterpiece': 150,
 'Zombies': 335,
 'Short': 447,
 'Puzzle': 1849,
 'Dystopian ': 162,
 'Physics': 388,
 'Horror': 1134,
 'Sandbox': 897,
 'Realistic': 400,
 'Massively Multiplayer': 464,
 'Comedy': 1018,
 'Episodic': 65,
 'Cinematic': 106,
 'Puzzle-Platformer': 423,
 '3D Platformer': 187,
 'Female Protagonist': 1222,
 'Funny': 1462,
 'Platformer': 1278,
 'Science': 71,
 'Dark Humor': 224,
 'Post-apocalyptic': 404,
 'Free to Play': 488,
 'Hero Shooter': 25,
 'Cartoony': 211,
 'Trading': 70,
 'Robots': 269,
 'Cartoon': 132,
 'Crafting': 370,
 'Replay Value': 517,
 'Survival Horror': 329,
 'Local Co-Op': 736,
 'MOBA': 107,
 'RTS': 548,
 'Tower Defense': 237,
 'RPG': 2798,
 'Fantasy': 1586,
 'Character Customization': 444,
 'Action RPG': 683,
 'Action-Adventure': 389,
 'Level Editor': 203,
 'Top-Down': 479,
 'Top-Down Shooter': 142,
 'Third Person': 1169,
 'PvE': 150,
 'Third-Person Shooter': 357,
 'Space': 661,
 'Fast-Paced': 381,
 '2D Fighter': 56,
 'Martial Arts': 30,
 'Intentionally Awkward Controls': 18,
 'Indie': 5736,
 'Fighting': 217,
 '2D': 2226,
 'Tanks': 63,
 'Cyberpunk': 317,
 'Futuristic': 302,
 'Hacking': 61,
 'Real-Time with Pause': 219,
 'Experimental': 113,
 'Addictive': 165,
 'Perma Death': 221,
 'Rogue-like': 533,
 'Wargame': 107,
 'Cold War': 74,
 'Psychological Horror': 487,
 'Diplomacy': 42,
 'Naval Combat': 30,
 'Naval': 63,
 'Submarine': 13,
 '4X': 195,
 'Turn-Based Strategy': 591,
 'Turn-Based': 807,
 'Dark Fantasy': 371,
 'Gothic': 104,
 'Isometric': 566,
 'Underground': 5,
 'Immersive Sim': 57,
 'Exploration': 1097,
 'Magic': 326,
 'Dungeon Crawler': 349,
 'Stealth': 546,
 'Inventory Management': 69,
 'Base-Building': 255,
 'Real-Time': 154,
 'Pixel Graphics': 971,
 'Resource Management': 236,
 'Tactical RPG': 194,
 'Medieval': 314,
 'Hack and Slash': 641,
 'Swordplay': 69,
 'Multiple Endings': 293,
 'Arena Shooter': 77,
 'Demons': 77,
 'Lovecraftian': 167,
 'Mystery': 513,
 'Stylized': 231,
 'Blood': 85,
 'Twin Stick Shooter': 162,
 "Shoot 'Em Up": 228,
 'Combat': 66,
 'Casual': 1979,
 'Flight': 159,
 '2D Platformer': 76,
 'Vampire': 57,
 'Cult Classic': 213,
 'Supernatural': 68,
 'Immersive': 40,
 'Western': 57,
 'Bullet Time': 62,
 'America': 50,
 'Controller': 732,
 'Management': 495,
 'Building': 372,
 'Economy': 222,
 'Family Friendly': 533,
 'City Builder': 210,
 'Political': 91,
 '3D': 219,
 'Destruction': 157,
 'Politics': 74,
 'Space Sim': 126,
 'Capitalism': 43,
 'Underwater': 60,
 'Combat Racing': 42,
 'Racing': 436,
 'Automobile Sim': 182,
 'Vehicular Combat': 57,
 'Music': 202,
 'Driving': 235,
 'Arcade': 707,
 'Local Multiplayer': 660,
 'Hex Grid': 122,
 'Turn-Based Combat': 335,
 'Point & Click': 764,
 'Word Game': 7,
 'Match 3': 54,
 'Cute': 623,
 'Touch-Friendly': 138,
 'Sniper': 14,
 'Comic Book': 84,
 'Villain Protagonist': 90,
 'Parody ': 66,
 'God Game': 48,
 'Colorful': 514,
 'Mature': 185,
 'Psychological': 91,
 'Surreal': 313,
 'Collectathon': 20,
 '3D Vision': 105,
 'Grand Strategy': 205,
 'Pirates': 84,
 'Sailing': 18,
 'Remake': 178,
 'Choose Your Own Adventure': 155,
 'Rome': 41,
 'Sports': 463,
 'Loot': 227,
 'Based On A Novel': 56,
 'Mythology': 93,
 'Epic': 76,
 'Warhammer 40K': 51,
 'Games Workshop': 68,
 'Real Time Tactics': 156,
 'Crime': 166,
 'Detective': 237,
 "Beat 'em up": 227,
 'Thriller': 110,
 'Side Scroller': 566,
 'Offroad': 52,
 'Motorbike': 18,
 'Bikes': 33,
 'Beautiful': 276,
 'Nudity': 356,
 'Mechs': 105,
 'Spectacle fighter': 41,
 'Character Action Game': 59,
 'Conspiracy': 38,
 'Transhumanism': 28,
 'Illuminati': 59,
 'Steampunk': 271,
 'Parkour': 199,
 'Modern': 32,
 'Lara Croft': 9,
 'Party-Based RPG': 131,
 'Romance': 103,
 'Choices Matter': 543,
 'CRPG': 171,
 'Time Attack': 51,
 'Anime': 508,
 'Trains': 44,
 'Alternate History': 126,
 'Mod': 20,
 'Dinosaurs': 47,
 'Heist': 59,
 'Split Screen': 186,
 'Bullet Hell': 188,
 'Psychedelic': 75,
 'MMORPG': 235,
 'Spaceships': 22,
 'Education': 95,
 'Philosophical': 45,
 'Time Travel': 87,
 'Superhero': 90,
 'Looter Shooter': 28,
 'Mars': 34,
 'Co-op Campaign': 78,
 'Relaxing': 287,
 'Time Manipulation': 65,
 'Turn-Based Tactics': 328,
 'Hunting': 26,
 'Investigation': 51,
 'Hidden Object': 55,
 '2.5D': 185,
 'Sequel': 27,
 '4 Player Local': 259,
 'Medical Sim': 18,
 'Noir': 106,
 'Narrative': 33,
 'Satire': 68,
 'Bowling': 6,
 'Soundtrack': 52,
 'Walking Simulator': 416,
 'Rhythm': 110,
 'Music-Based Procedural Generation': 28,
 'Procedural Generation': 359,
 'Ninja': 99,
 'Nostalgia': 13,
 'Minigames': 33,
 'Emotional': 101,
 'TrackIR': 48,
 'VR': 315,
 'Werewolves': 22,
 'Benchmark': 11,
 'Colony Sim': 59,
 'Dragons': 86,
 'FMV': 60,
 '6DOF': 38,
 'Well-Written': 8,
 'LEGO': 22,
 'Quick-Time Events': 43,
 'Voice Control': 7,
 'Logic': 34,
 'Memes': 200,
 'Gun Customization': 18,
 'Party': 15,
 'JRPG': 191,
 'Political Sim': 50,
 'Metroidvania': 341,
 'Hand-drawn': 314,
 'Experience': 30,
 'Interactive Fiction': 142,
 'Board Game': 112,
 'Ambient': 10,
 'Minimalist': 118,
 'Card Game': 164,
 'Gambling': 10,
 'Conversation': 32,
 'Mouse only': 74,
 'Drama': 135,
 'Visual Novel': 236,
 'Batman': 7,
 'Dog': 23,
 'Abstract': 75,
 'Life Sim': 40,
 'Precision Platformer': 41,
 'Unforgiving': 14,
 'Horses': 21,
 'Lore-Rich': 78,
 'Sexual Content': 181,
 'Action Roguelike': 276,
 'Strategy RPG': 113,
 'Cats': 46,
 'Card Battler': 38,
 'Deckbuilding': 75,
 'Trading Card Game': 49,
 'Rogue-lite': 453,
 'Tennis': 6,
 'Transportation': 15,
 'Nature': 57,
 'Kickstarter': 246,
 'Programming': 41,
 'Automation': 25,
 'Party Game': 25,
 'GameMaker': 47,
 'Asynchronous Multiplayer': 34,
 'Chess': 14,
 'Traditional Roguelike': 16,
 'Dungeons & Dragons': 15,
 'On-Rails Shooter': 11,
 'Open World Survival Craft': 98,
 'Narration': 134,
 'Dynamic Narration': 52,
 'Grid-Based Movement': 74,
 'Basketball': 11,
 'Movie': 17,
 'Artificial Intelligence': 33,
 'Reboot': 11,
 'RPGMaker': 41,
 'Roguevania': 18,
 'LGBTQ+': 76,
 'Dating Sim': 57,
 'Text-Based': 46,
 'Nonlinear': 50,
 'Souls-like': 131,
 'Pinball': 17,
 '3D Fighter': 16,
 'Runner': 29,
 'Crowdfunded': 60,
 'Dark Comedy': 67,
 'Early Access': 438,
 'Star Wars': 2,
 'Football': 43,
 'Soccer': 30,
 'Tabletop': 56,
 'Fishing': 37,
 'Typing': 32,
 'Wrestling': 18,
 'Sokoban': 8,
 'Voxel': 33,
 'Mystery Dungeon': 16,
 'Archery': 8,
 'Mining': 16,
 'Lemmings': 22,
 'Roguelike Deckbuilder': 32,
 'Golf': 18,
 'VR Only': 72,
 'Time Management': 20,
 'Tutorial': 12,
 'Mini Golf': 11,
 'Skateboarding': 10,
 'Skating': 14,
 'Pool': 3,
 'Hentai': 3,
 'Otome': 5,
 'Agriculture': 44,
 'Farming Sim': 35,
 'Spelling': 2,
 'Design & Illustration': 8,
 'Animation & Modeling': 15,
 'Asymmetric VR': 1,
 'Clicker': 16,
 'Philisophical': 5,
 'Motocross': 5,
 'ATV': 2,
 'Steam Machine': 3,
 'Boxing': 5,
 'Baseball': 15,
 'Cycling': 15,
 'Documentary': 8,
 'Battle Royale': 20,
 'Audio Production': 3,
 'Snowboarding': 2,
 'Skiing': 7,
 'Hockey': 6,
 'NSFW': 9,
 'Farming': 7,
 'Snow': 14,
 'Creature Collector': 1,
 'BMX': 3,
 'Faith': 6,
 'Idler': 8,
 'Foreign': 8,
 'Social Deduction': 3,
 'Utilities': 5,
 'Video Production': 5,
 'Game Development': 3,
 'Trivia': 2,
 'Auto Battler': 1}

In [15]:
tag_explode = genre_explode.explode("Tags")
tag_explode

,App Id,Name,Developers,Publishers,Metascores,Genres,Tags,Price,min owners,max owners
2,10,Counter-Strike,Valve,Valve,88%,Action,Action,$9.99,"10,000,000","20,000,000"
2,10,Counter-Strike,Valve,Valve,88%,Action,FPS,$9.99,"10,000,000","20,000,000"
2,10,Counter-Strike,Valve,Valve,88%,Action,Multiplayer,$9.99,"10,000,000","20,000,000"
2,10,Counter-Strike,Valve,Valve,88%,Action,Shooter,$9.99,"10,000,000","20,000,000"
2,10,Counter-Strike,Valve,Valve,88%,Action,Classic,$9.99,"10,000,000","20,000,000"
...,...,...,...,...,...,...,...,...,...,...
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Colorful,$39.99,"50,000","100,000"
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Cats,$39.99,"50,000","100,000"
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Dog,$39.99,"50,000","100,000"
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Singleplayer,$39.99,"50,000","100,000"
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Loot,$39.99,"50,000","100,000"

In [35]:
tag_explode['max owners'] = tag_explode['max owners'].replace(",","")
# tag_explode.dtypes
tag_explode.head()

,App Id,Name,Developers,Publishers,Metascores,Genres,Tags,Price,min owners,max owners
2,10,Counter-Strike,Valve,Valve,88%,Action,Action,$9.99,"10,000,000","20,000,000"
2,10,Counter-Strike,Valve,Valve,88%,Action,FPS,$9.99,"10,000,000","20,000,000"
2,10,Counter-Strike,Valve,Valve,88%,Action,Multiplayer,$9.99,"10,000,000","20,000,000"
2,10,Counter-Strike,Valve,Valve,88%,Action,Shooter,$9.99,"10,000,000","20,000,000"
2,10,Counter-Strike,Valve,Valve,88%,Action,Classic,$9.99,"10,000,000","20,000,000"

In [39]:
x = tag_explode["max owners"].iloc[0]

In [40]:
x.replace(",", "")

'20000000'

In [44]:
tag_explode["max owners"] = pd.Series(tag_explode["max owners"]).str.replace(',', "")
tag_explode.head()

,App Id,Name,Developers,Publishers,Metascores,Genres,Tags,Price,min owners,max owners
2,10,Counter-Strike,Valve,Valve,88%,Action,Action,$9.99,"10,000,000",20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,FPS,$9.99,"10,000,000",20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,Multiplayer,$9.99,"10,000,000",20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,Shooter,$9.99,"10,000,000",20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,Classic,$9.99,"10,000,000",20000000

In [45]:
tag_explode["min owners"] = pd.Series(tag_explode["min owners"]).str.replace(',', "")
tag_explode.head()

,App Id,Name,Developers,Publishers,Metascores,Genres,Tags,Price,min owners,max owners
2,10,Counter-Strike,Valve,Valve,88%,Action,Action,$9.99,10000000,20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,FPS,$9.99,10000000,20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,Multiplayer,$9.99,10000000,20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,Shooter,$9.99,10000000,20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,Classic,$9.99,10000000,20000000

In [47]:
tag_explode

,App Id,Name,Developers,Publishers,Metascores,Genres,Tags,Price,min owners,max owners
2,10,Counter-Strike,Valve,Valve,88%,Action,Action,$9.99,10000000,20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,FPS,$9.99,10000000,20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,Multiplayer,$9.99,10000000,20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,Shooter,$9.99,10000000,20000000
2,10,Counter-Strike,Valve,Valve,88%,Action,Classic,$9.99,10000000,20000000
...,...,...,...,...,...,...,...,...,...,...
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Colorful,$39.99,50000,100000
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Cats,$39.99,50000,100000
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Dog,$39.99,50000,100000
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Singleplayer,$39.99,50000,100000
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Loot,$39.99,50000,100000

In [50]:
own_med = tag_explode["max owners"].median()
own_med
own_max = tag_explode["max owners"].max()
own_max
own_med

200000.0

In [54]:
tag_explode['max owners'] = tag_explode['max owners'].astype(int)

In [55]:
tag_explode.loc[tag_explode["max owners"]>= 200000.0, "Hit"] = 1
tag_explode.loc[tag_explode["max owners"]< 200000.0, "Hit"] = 0

In [56]:
tag_explode

,App Id,Name,Developers,Publishers,Metascores,Genres,Tags,Price,min owners,max owners,Hit
2,10,Counter-Strike,Valve,Valve,88%,Action,Action,$9.99,10000000,20000000,1.0
2,10,Counter-Strike,Valve,Valve,88%,Action,FPS,$9.99,10000000,20000000,1.0
2,10,Counter-Strike,Valve,Valve,88%,Action,Multiplayer,$9.99,10000000,20000000,1.0
2,10,Counter-Strike,Valve,Valve,88%,Action,Shooter,$9.99,10000000,20000000,1.0
2,10,Counter-Strike,Valve,Valve,88%,Action,Classic,$9.99,10000000,20000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Colorful,$39.99,50000,100000,0.0
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Cats,$39.99,50000,100000,0.0
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Dog,$39.99,50000,100000,0.0
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Singleplayer,$39.99,50000,100000,0.0
88688,1356670,Sakuna: Of Rice and Ruin,Edelweiss,XSEED Games,79%,Indie,Loot,$39.99,50000,100000,0.0

In [59]:
tag_explode.to_csv('final_project_hits.csv', index = False, header=True)